name: dl_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - pytorch
  - torchvision
  - pandas
  - ipykernel
  - notebook
  - matplotlib
  - scikit-learn
  - geopandas
  - jupyterlab
  - pip:
      - torchsummary
      - tqdm